[package]
name = "packageurl"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]

[dependencies]
percent-encoding = "*"
error-chain = "*"
serde = { version = "*", optional = true}
memchr = { version = "*", optional = true}

[dev-dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
lazy_static = "*"
url = "*"
